### ISSUE TITLE
No ability to set duration for switch

### ISSUE THREAD

**Issue by WojtekK78** [konikvranik/hacs_rainbird#10]
How to setup "duration" when turning particular switch on. In original integration we could use _start_irrigation_ service which allowed for _duration_. That service is no longer available in HCAS version. 

Currently I don't see easy option to set duration when switching sprinklers on. Service to turn on switch do not allow for data and if used as below throws error _Failed to call service switch.turn_on. extra keys not allowed @ data['duration']. Got None_

```
service: switch.turn_on
data:
  duration: 10
target:
  entity_id: switch.mainlawn
```
_Rainbird.command_ looks even more complex then switch.turn_on when I'm looking at implementation

**Comment by konikvranik** [comment]
I've just added new service to turn on the zone with irrigation time:
```yaml
service: rainbird.start_zone
data:
  zone_run_time: 60
target:
  entity_id: switch.rainbird_rainbird_home_1
```
